reg add HKEY_CLASSES_ROOT\*\shell\OpenOmmBuilder /f /ve /t REG_SZ /d "Open OMM Builder here"
reg add HKEY_CLASSES_ROOT\*\shell\OpenOmmBuilder /f /v "Icon" /t REG_SZ /d "%appdata%\msys2\mingw64.exe"
reg add HKEY_CLASSES_ROOT\*\shell\OpenOmmBuilder\command /f /ve /t REG_SZ /d "%appdata%\msys2\mingw64.exe bash -c \"python3 omm_builder.py\""
reg add HKEY_CLASSES_ROOT\Directory\shell\OpenOmmBuilder /f /ve /t REG_SZ /d "Open OMM Builder here"
reg add HKEY_CLASSES_ROOT\Directory\shell\OpenOmmBuilder /f /v "Icon" /t REG_SZ /d "%appdata%\msys2\mingw64.exe"
reg add HKEY_CLASSES_ROOT\Directory\shell\OpenOmmBuilder\command /f /ve /t REG_SZ /d "%appdata%\msys2\mingw64.exe bash -c \"python3 omm_builder.py\""
reg add HKEY_CLASSES_ROOT\Directory\Background\shell\OpenOmmBuilder /f /ve /t REG_SZ /d "Open OMM Builder here"
reg add HKEY_CLASSES_ROOT\Directory\Background\shell\OpenOmmBuilder /f /v "Icon" /t REG_SZ /d "%appdata%\msys2\mingw64.exe"
reg add HKEY_CLASSES_ROOT\Directory\Background\shell\OpenOmmBuilder\command /f /ve /t REG_SZ /d "%appdata%\msys2\mingw64.exe bash -c \"python3 omm_builder.py\""
