reg add HKEY_CLASSES_ROOT\*\shell\OpenMinGW64 /f /ve /t REG_SZ /d "Open MinGW64 here"
reg add HKEY_CLASSES_ROOT\*\shell\OpenMinGW64 /f /v "Icon" /t REG_SZ /d "%appdata%\msys2\mingw64.exe"
reg add HKEY_CLASSES_ROOT\*\shell\OpenMinGW64\command /f /ve /t REG_SZ /d "%appdata%\msys2\mingw64.exe bash"
reg add HKEY_CLASSES_ROOT\Directory\shell\OpenMinGW64 /f /ve /t REG_SZ /d "Open MinGW64 here"
reg add HKEY_CLASSES_ROOT\Directory\shell\OpenMinGW64 /f /v "Icon" /t REG_SZ /d "%appdata%\msys2\mingw64.exe"
reg add HKEY_CLASSES_ROOT\Directory\shell\OpenMinGW64\command /f /ve /t REG_SZ /d "%appdata%\msys2\mingw64.exe bash"
reg add HKEY_CLASSES_ROOT\Directory\Background\shell\OpenMinGW64 /f /ve /t REG_SZ /d "Open MinGW64 here"
reg add HKEY_CLASSES_ROOT\Directory\Background\shell\OpenMinGW64 /f /v "Icon" /t REG_SZ /d "%appdata%\msys2\mingw64.exe"
reg add HKEY_CLASSES_ROOT\Directory\Background\shell\OpenMinGW64\command /f /ve /t REG_SZ /d "%appdata%\msys2\mingw64.exe bash"
