extern const GeoLayout MolineC_geo[];
extern Vtx MolineC_WindMillCake__ck_WindMillCakeY_mesh_vtx_0[93];
extern Gfx MolineC_WindMillCake__ck_WindMillCakeY_mesh_tri_0[];
extern Vtx MolineC_WindMillCake__ck_WindMillCakeY_mesh_vtx_1[99];
extern Gfx MolineC_WindMillCake__ck_WindMillCakeY_mesh_tri_1[];
extern Vtx MolineC_WindMillCake__ck_WindMillCakeY_mesh_vtx_2[98];
extern Gfx MolineC_WindMillCake__ck_WindMillCakeY_mesh_tri_2[];
extern Vtx MolineC_WindMillCake__ck_WindMillCakeY_mesh_vtx_3[98];
extern Gfx MolineC_WindMillCake__ck_WindMillCakeY_mesh_tri_3[];
extern Vtx MolineC_WindMillCake__ck_WindMillCakeY_mesh_vtx_4[46];
extern Gfx MolineC_WindMillCake__ck_WindMillCakeY_mesh_tri_4[];
extern Vtx MolineC_WindMillCake__ck_WindMillCakeY_mesh_vtx_5[112];
extern Gfx MolineC_WindMillCake__ck_WindMillCakeY_mesh_tri_5[];

extern Gfx MolineC_WindMillCake__ck_WindMillCakeY_mesh[];
extern Gfx MolineC_material_revert_render_settings[];

