#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_Back_1_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -3736, 0, 0, bbh_dl_Back_2_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Back_3_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -3683, -1286, -120, bbh_dl_Bigtree_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 5476, -200, -1344, bbh_dl_Forest_1_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 0, -797, 5108, bbh_dl_Forest_2_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Playzone_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Playzone_2_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 2211, -2868, 6438, bbh_dl_Playzone_3_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 2211, -2868, 6438, bbh_dl_Playzone_4_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Playzone_5_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Stone_mesh),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_TreeShadow_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -1460, -1049, -3484, bbh_dl_Water_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
