COURSE_ACTS(COURSE_BOB, _(" 1 ARCHIPELAGO'S WATERFALLS"),
       _("BIG BOB-OMB COME BACK")     , _("ON THE HIGHEST ROCK") , _("HIDDEN ON THE CLIFF"),
       _("FIND THE 8 GREEN COINS")          , _("IN THE BOBOMB'S CAVE")        , _("HIDDEN IN THE CAVE"))

COURSE_ACTS(COURSE_WF, _(" 2 DOWN STREET"),
       _("PROBLEMS IN THE TOWER")        , _("HIDDEN IN THE TRASH")    , _("BOX IN THE BUILDING"),
       _("GREEN COINS IN THE CITY"), _("IN THE GREEN ROOF")    , _("FLOATING IN THE AIR"))

COURSE_ACTS(COURSE_JRB, _(" 3 JOLLY ROGER BAY"),
       _("PLUNDER IN THE SUNKEN SHIP")    , _("CAN THE EEL COME OUT TO PLAY?") , _("TREASURE OF THE OCEAN CAVE"),
       _("RED COINS ON THE SHIP AFLOAT")  , _("BLAST TO THE STONE PILLAR")     , _("THROUGH THE JET STREAM"))

COURSE_ACTS(COURSE_CCM, _(" 4 MELTED ICE"),
       _("PENGUIN LOST, AGAIN!")             , _("8 GREEN COINS IN THE SNOW")             , _("THE COLD FLOATING ISLAND"),
       _("SHINE IN THE MOUNTAIN TOP")  , _("5 GREEN COINS IN THE LAVA")       , _("STEPPING ON THE RED BLOCKS"))

COURSE_ACTS(COURSE_BBH, _(" 5 GREEN WOODS"),
       _("HAUNTED FOREST")            , _("UNDERWATER") , _("WALL JUMP BETWEEN THE WOODS"),
       _("8 GREEN COINS IN THE FOREST")          , _("ABOVE THE TREES")             , _("HIDDEN PIPE"))

COURSE_ACTS(COURSE_HMC, _(" 6 SKYLAND FORTRESS"),
       _("BOX IN THE TOP OF THE CASTLE")  , _("FLOATING IN THE BOW")       , _("IN THE HIGHEST TOWER"),
       _("FIND THE 8 GREEN COINS")     , _("CLIMBING THE FORTRESS")     , _("THE MYSTERY PIPE"))

COURSE_ACTS(COURSE_LLL, _(" 7 SWEET SWEET RUSH"),
       _("CLIMBING THE GIGANT CAKE")            , _("GREEN COINS IN THE SWEET PASS")             , _("8-COIN PUZZLE WITH 15 PIECES"),
       _("RED-HOT LOG ROLLING")           , _("HOT-FOOT-IT INTO THE VOLCANO")  , _("ELEVATOR TOUR IN THE VOLCANO"))

COURSE_ACTS(COURSE_SSL, _(" 8 YELLOW DUNES"),
       _("FIGHT WITH THE BIG ROCK") , _("8 GREEN COINS IN THE DESERT")      , _("INSIDE THE ANCIENT PYRAMID"),
       _("STAND TALL ON THE FOUR PILLARS"), _("FREE FLYING FOR 8 RED COINS")   , _("PYRAMID PUZZLE"))

COURSE_ACTS(COURSE_DDD, _(" 9 DIRE, DIRE DOCKS"),
       _("BOARD BOWSER'S SUB")            , _("CHESTS IN THE CURRENT")         , _("POLE-JUMPING FOR RED COINS"),
       _("THROUGH THE JET STREAM")        , _("THE MANTA RAY'S REWARD")        , _("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("10 SNOWMAN'S LAND"),
       _("SNOWMAN'S BIG HEAD")            , _("CHILL WITH THE BULLY")          , _("IN THE DEEP FREEZE"),
       _("WHIRL FROM THE FREEZING POND")  , _("SHELL SHREDDIN' FOR RED COINS") , _("INTO THE IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11 GREEN PLAINS"),
       _("QUIET WALK")         , _("WALL JUMPING")               , _("LOOKING FOR DIAMONDS IN THE CAVE"),
       _("GREEN COINS IN THE WAY")   , _("GO TO TOWN FOR RED COINS")      , _("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 TALL, TALL MOUNTAIN"),
       _("SCALE THE MOUNTAIN")            , _("MYSTERY OF THE MONKEY CAGE")    , _("SCARY 'SHROOMS, RED COINS"),
       _("MYSTERIOUS MOUNTAINSIDE")       , _("BREATHTAKING VIEW FROM BRIDGE") , _("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 TINY-HUGE ISLAND"),
       _("PLUCK THE PIRANHA FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("REMATCH WITH KOOPA THE QUICK"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 TICK TOCK CLOCK"),
       _("ROLL INTO THE CAGE")            , _("THE PIT AND THE PENDULUMS")     , _("GET A HAND"),
       _("STOMP ON THE THWOMP")           , _("TIMED JUMPS ON MOVING BARS")    , _("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 RAINBOW RIDE"),
       _("CRUISER CROSSING THE RAINBOW")  , _("THE BIG HOUSE IN THE SKY")      , _("COINS AMASSED IN A MAZE"),
       _("SWINGIN' IN THE BREEZE")        , _("TRICKY TRIANGLES!")             , _("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER IN THE DARK WORLD"))
SECRET_STAR(COURSE_BITFS, _("   PURPLE SWAMPY SWAMP"))
SECRET_STAR(COURSE_BITS, _("   MOONSHINE"))
SECRET_STAR(COURSE_PSS, _("   FOREST VALLEY"))
SECRET_STAR(COURSE_COTMC, _("   CAVERN OF THE METAL CAP"))
SECRET_STAR(COURSE_TOTWC, _("   TOWER OF THE WING CAP"))
SECRET_STAR(COURSE_VCUTM, _("   VANISH CAP UNDER THE MOAT"))
SECRET_STAR(COURSE_WMOTR, _("   WING MARIO OVER THE RAINBOW"))
SECRET_STAR(COURSE_SA, _("   THE SECRET AQUARIUM"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   CASTLE SECRET STARS"))

EXTRA_TEXT(0, _("ONE OF THE CASTLE'S SECRET STARS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
