extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern const GeoLayout ssl_area_2_geo[];
extern const GeoLayout ssl_area_2[];
extern const Collision ssl_area_2_collision[];
extern const MacroObject ssl_area_2_macro_objs[];
extern Vtx ssl_dl_Back_mesh_vtx_0[2842];
extern Gfx ssl_dl_Back_mesh_tri_0[];
extern Vtx ssl_dl_Back_mesh_vtx_1[2420];
extern Gfx ssl_dl_Back_mesh_tri_1[];
extern Vtx ssl_dl_Back_mesh_vtx_2[9585];
extern Gfx ssl_dl_Back_mesh_tri_2[];
extern Vtx ssl_dl_Back_mesh_vtx_3[19909];
extern Gfx ssl_dl_Back_mesh_tri_3[];
extern Vtx ssl_dl_Back_mesh_vtx_4[124];
extern Gfx ssl_dl_Back_mesh_tri_4[];
extern Vtx ssl_dl_Part1_mesh_vtx_0[12519];
extern Gfx ssl_dl_Part1_mesh_tri_0[];
extern Vtx ssl_dl_Part1_mesh_vtx_1[848];
extern Gfx ssl_dl_Part1_mesh_tri_1[];
extern Vtx ssl_dl_Part1_mesh_vtx_2[87];
extern Gfx ssl_dl_Part1_mesh_tri_2[];
extern Vtx ssl_dl_Part1_mesh_vtx_3[7038];
extern Gfx ssl_dl_Part1_mesh_tri_3[];
extern Vtx ssl_dl_Part1_mesh_vtx_4[1098];
extern Gfx ssl_dl_Part1_mesh_tri_4[];
extern Vtx ssl_dl_Playzone_mesh_vtx_0[155];
extern Gfx ssl_dl_Playzone_mesh_tri_0[];
extern Vtx ssl_dl_Playzone_mesh_vtx_1[35];
extern Gfx ssl_dl_Playzone_mesh_tri_1[];
extern Vtx ssl_dl_Playzone2_mesh_vtx_0[135];
extern Gfx ssl_dl_Playzone2_mesh_tri_0[];
extern Vtx ssl_dl_Playzone2_mesh_vtx_1[22];
extern Gfx ssl_dl_Playzone2_mesh_tri_1[];
extern Vtx ssl_dl_Transparent_mesh_vtx_0[8];
extern Gfx ssl_dl_Transparent_mesh_tri_0[];
extern Vtx ssl_dl_Party1_mesh_vtx_0[56];
extern Gfx ssl_dl_Party1_mesh_tri_0[];
extern Vtx ssl_dl_Party1_mesh_vtx_1[157];
extern Gfx ssl_dl_Party1_mesh_tri_1[];
extern Vtx ssl_dl_Party1_mesh_vtx_2[596];
extern Gfx ssl_dl_Party1_mesh_tri_2[];
extern Vtx ssl_dl_Party1_mesh_vtx_3[4];
extern Gfx ssl_dl_Party1_mesh_tri_3[];
extern Vtx ssl_dl_Party1_mesh_vtx_4[3170];
extern Gfx ssl_dl_Party1_mesh_tri_4[];
extern Vtx ssl_dl_Transparent2_mesh_vtx_0[12];
extern Gfx ssl_dl_Transparent2_mesh_tri_0[];

extern Gfx ssl_dl_Back_mesh[];
extern Gfx ssl_dl_Part1_mesh[];
extern Gfx ssl_dl_Playzone_mesh[];
extern Gfx ssl_dl_Playzone2_mesh[];
extern Gfx ssl_dl_Transparent_mesh[];
extern Gfx ssl_dl_Party1_mesh[];
extern Gfx ssl_dl_Transparent2_mesh[];
extern Gfx ssl_dl_material_revert_render_settings[];

