#include "src/game/envfx_snow.h"

const GeoLayout geoinc[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, geo_cannon_circle_base),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, JollyChad_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, JollyChad_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, JollyChad_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, JollyChad_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, JollyChad_001_displaylist_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, JollyChad_002_displaylist_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, JollyChad_003_displaylist_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, JollyChad_004_displaylist_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, JollyChad_005_displaylist_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, JollyChad_006_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, JollyChad_006_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, geo_movtex_pause_control),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(4609, geo_movtex_draw_water_regions),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(4613, geo_movtex_draw_water_regions),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(14, geo_envfx_main),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
