extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Vtx bob_dl_Back_mesh_vtx_0[999];
extern Gfx bob_dl_Back_mesh_tri_0[];
extern Vtx bob_dl_Back_mesh_vtx_1[61];
extern Gfx bob_dl_Back_mesh_tri_1[];
extern Vtx bob_dl_Back_mesh_vtx_2[1761];
extern Gfx bob_dl_Back_mesh_tri_2[];
extern Vtx bob_dl_Backwater_mesh_vtx_0[4];
extern Gfx bob_dl_Backwater_mesh_tri_0[];
extern Vtx bob_dl_Cube_mesh_vtx_0[251];
extern Gfx bob_dl_Cube_mesh_tri_0[];
extern Vtx bob_dl_Cube_mesh_vtx_1[41];
extern Gfx bob_dl_Cube_mesh_tri_1[];
extern Vtx bob_dl_Cube_mesh_vtx_2[489];
extern Gfx bob_dl_Cube_mesh_tri_2[];
extern Vtx bob_dl_Cube_mesh_vtx_3[101];
extern Gfx bob_dl_Cube_mesh_tri_3[];
extern Vtx bob_dl_Cube_mesh_vtx_4[87];
extern Gfx bob_dl_Cube_mesh_tri_4[];
extern Vtx bob_dl_Cube_mesh_vtx_5[68];
extern Gfx bob_dl_Cube_mesh_tri_5[];
extern Vtx bob_dl_Cube_mesh_vtx_6[687];
extern Gfx bob_dl_Cube_mesh_tri_6[];
extern Vtx bob_dl_Cube_mesh_vtx_7[80];
extern Gfx bob_dl_Cube_mesh_tri_7[];
extern Vtx bob_dl_Cube_mesh_vtx_8[12];
extern Gfx bob_dl_Cube_mesh_tri_8[];
extern Vtx bob_dl_Cube_mesh_vtx_9[14];
extern Gfx bob_dl_Cube_mesh_tri_9[];
extern Vtx bob_dl_Cube_mesh_vtx_10[12];
extern Gfx bob_dl_Cube_mesh_tri_10[];
extern Vtx bob_dl_Cube_mesh_vtx_11[6];
extern Gfx bob_dl_Cube_mesh_tri_11[];
extern Vtx bob_dl_Cube_mesh_vtx_12[211];
extern Gfx bob_dl_Cube_mesh_tri_12[];
extern Vtx bob_dl_Cube_mesh_vtx_13[18];
extern Gfx bob_dl_Cube_mesh_tri_13[];
extern Vtx bob_dl_Fossil_mesh_vtx_0[574];
extern Gfx bob_dl_Fossil_mesh_tri_0[];
extern Vtx bob_dl_Plataforms_mesh_vtx_0[160];
extern Gfx bob_dl_Plataforms_mesh_tri_0[];
extern Vtx bob_dl_Plataforms_mesh_vtx_1[160];
extern Gfx bob_dl_Plataforms_mesh_tri_1[];
extern Vtx bob_dl_Plataforms_mesh_vtx_2[40];
extern Gfx bob_dl_Plataforms_mesh_tri_2[];
extern Vtx bob_dl_Plataforms_mesh_vtx_3[40];
extern Gfx bob_dl_Plataforms_mesh_tri_3[];
extern Vtx bob_dl_Waterpart_mesh_vtx_0[4];
extern Gfx bob_dl_Waterpart_mesh_tri_0[];
extern Vtx bob_dl_Waterpart_mesh_vtx_1[36];
extern Gfx bob_dl_Waterpart_mesh_tri_1[];
extern Vtx bob_dl_Waterpart_mesh_vtx_2[16];
extern Gfx bob_dl_Waterpart_mesh_tri_2[];

extern Gfx bob_dl_Back_mesh[];
extern Gfx bob_dl_Backwater_mesh[];
extern Gfx bob_dl_Cube_mesh[];
extern Gfx bob_dl_Fossil_mesh[];
extern Gfx bob_dl_Plataforms_mesh[];
extern Gfx bob_dl_Waterpart_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];

