extern const GeoLayout bits_area_1_geo[];
extern const GeoLayout bits_area_1[];
extern const Collision bits_area_1_collision[];
extern const MacroObject bits_area_1_macro_objs[];
extern Vtx bits_dl_Back1_mesh_vtx_0[524];
extern Gfx bits_dl_Back1_mesh_tri_0[];
extern Vtx bits_dl_Back1_mesh_vtx_1[513];
extern Gfx bits_dl_Back1_mesh_tri_1[];
extern Vtx bits_dl_Part1_mesh_vtx_0[14470];
extern Gfx bits_dl_Part1_mesh_tri_0[];
extern Vtx bits_dl_Part1_mesh_vtx_1[13743];
extern Gfx bits_dl_Part1_mesh_tri_1[];
extern Vtx bits_dl_Part1_mesh_vtx_2[2947];
extern Gfx bits_dl_Part1_mesh_tri_2[];
extern Vtx bits_dl_Part2_mesh_vtx_0[7299];
extern Gfx bits_dl_Part2_mesh_tri_0[];
extern Vtx bits_dl_Part2_mesh_vtx_1[48];
extern Gfx bits_dl_Part2_mesh_tri_1[];
extern Vtx bits_dl_Part2_mesh_vtx_2[675];
extern Gfx bits_dl_Part2_mesh_tri_2[];
extern Vtx bits_dl_Part2_mesh_vtx_3[3880];
extern Gfx bits_dl_Part2_mesh_tri_3[];
extern Vtx bits_dl_Transparent_mesh_vtx_0[522];
extern Gfx bits_dl_Transparent_mesh_tri_0[];
extern Vtx bits_dl_Transparent_mesh_vtx_1[24];
extern Gfx bits_dl_Transparent_mesh_tri_1[];
extern Vtx bits_dl_Transparent_mesh_vtx_2[4];
extern Gfx bits_dl_Transparent_mesh_tri_2[];
extern Vtx bits_dl_Transparent_mesh_vtx_3[4];
extern Gfx bits_dl_Transparent_mesh_tri_3[];
extern Vtx bits_dl_Transparent_mesh_vtx_4[4];
extern Gfx bits_dl_Transparent_mesh_tri_4[];
extern Vtx bits_dl_Transparent_mesh_vtx_5[12];
extern Gfx bits_dl_Transparent_mesh_tri_5[];

extern Gfx bits_dl_Back1_mesh[];
extern Gfx bits_dl_Part1_mesh[];
extern Gfx bits_dl_Part2_mesh[];
extern Gfx bits_dl_Transparent_mesh[];
extern Gfx bits_dl_material_revert_render_settings[];

