extern const GeoLayout bitfs_area_1_geo[];
extern const GeoLayout bitfs_area_1[];
extern const Collision bitfs_area_1_collision[];
extern const MacroObject bitfs_area_1_macro_objs[];
extern Vtx bitfs_dl_Back_mesh_vtx_0[14];
extern Gfx bitfs_dl_Back_mesh_tri_0[];
extern Vtx bitfs_dl_Back_mesh_vtx_1[187];
extern Gfx bitfs_dl_Back_mesh_tri_1[];
extern Vtx bitfs_dl_Part1_mesh_vtx_0[2302];
extern Gfx bitfs_dl_Part1_mesh_tri_0[];
extern Vtx bitfs_dl_Part1_mesh_vtx_1[1946];
extern Gfx bitfs_dl_Part1_mesh_tri_1[];
extern Vtx bitfs_dl_Part1_mesh_vtx_2[9201];
extern Gfx bitfs_dl_Part1_mesh_tri_2[];
extern Vtx bitfs_dl_Part1_mesh_vtx_3[178];
extern Gfx bitfs_dl_Part1_mesh_tri_3[];
extern Vtx bitfs_dl_Part1_mesh_vtx_4[1126];
extern Gfx bitfs_dl_Part1_mesh_tri_4[];
extern Vtx bitfs_dl_Part1_mesh_vtx_5[293];
extern Gfx bitfs_dl_Part1_mesh_tri_5[];
extern Vtx bitfs_dl_Part1_mesh_vtx_6[1483];
extern Gfx bitfs_dl_Part1_mesh_tri_6[];
extern Vtx bitfs_dl_Part1_mesh_vtx_7[4445];
extern Gfx bitfs_dl_Part1_mesh_tri_7[];
extern Vtx bitfs_dl_Part1_mesh_vtx_8[393];
extern Gfx bitfs_dl_Part1_mesh_tri_8[];
extern Vtx bitfs_dl_Part1_mesh_vtx_9[5120];
extern Gfx bitfs_dl_Part1_mesh_tri_9[];
extern Vtx bitfs_dl_Part1_mesh_vtx_10[6616];
extern Gfx bitfs_dl_Part1_mesh_tri_10[];
extern Vtx bitfs_dl_Part1_mesh_vtx_11[9414];
extern Gfx bitfs_dl_Part1_mesh_tri_11[];
extern Vtx bitfs_dl_Part1_mesh_vtx_12[135];
extern Gfx bitfs_dl_Part1_mesh_tri_12[];
extern Vtx bitfs_dl_Part1_mesh_vtx_13[10];
extern Gfx bitfs_dl_Part1_mesh_tri_13[];
extern Vtx bitfs_dl_Part2_mesh_vtx_0[812];
extern Gfx bitfs_dl_Part2_mesh_tri_0[];
extern Vtx bitfs_dl_Part2_mesh_vtx_1[144];
extern Gfx bitfs_dl_Part2_mesh_tri_1[];
extern Vtx bitfs_dl_Part2_mesh_vtx_2[171];
extern Gfx bitfs_dl_Part2_mesh_tri_2[];
extern Vtx bitfs_dl_Part2_mesh_vtx_3[3159];
extern Gfx bitfs_dl_Part2_mesh_tri_3[];
extern Vtx bitfs_dl_Part2_mesh_vtx_4[15841];
extern Gfx bitfs_dl_Part2_mesh_tri_4[];
extern Vtx bitfs_dl_Part2_mesh_vtx_5[224];
extern Gfx bitfs_dl_Part2_mesh_tri_5[];
extern Vtx bitfs_dl_Transparent_mesh_vtx_0[36];
extern Gfx bitfs_dl_Transparent_mesh_tri_0[];
extern Vtx bitfs_dl_Transparent_mesh_vtx_1[842];
extern Gfx bitfs_dl_Transparent_mesh_tri_1[];
extern Vtx bitfs_dl_Transparent_mesh_vtx_2[71];
extern Gfx bitfs_dl_Transparent_mesh_tri_2[];

extern Gfx bitfs_dl_Back_mesh[];
extern Gfx bitfs_dl_Part1_mesh[];
extern Gfx bitfs_dl_Part2_mesh[];
extern Gfx bitfs_dl_Transparent_mesh[];
extern Gfx bitfs_dl_material_revert_render_settings[];

